FUTURES_A_SOURCE = "../futuresA.csv"
FUTURES_A_DATE_COLUMN_NAME = "Date"
FUTURES_A_PRICE_COLUMN_NAME = "Last"

FUTURES_B_SOURCE = "../futuresB.csv"
FUTURES_B_DATE_COLUMN_NAME = "Date"
FUTURES_B_PRICE_COLUMN_NAME = "Close"

X = 1
Y = 1
N = 20
L = 1
S = -1
C = 0.001

ANNUAL_TRADING_DAYS = 252
